apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: dev
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: dev
    spec:
      containers:
      - name: dev
        image: docker-registry.pdxhome.greghaynes.net/go-dev
        imagePullPolicy: Always
        ports:
        - containerPort: 22
        command:
          - /usr/sbin/sshd
          - "-D"
